package io.github.yallain.rrule

import kotlinx.datetime.LocalDateTime
import kotlin.time.Instant

/** Resolves local calendar fields against the rules of an iCalendar time-zone identifier. */
public fun interface RecurrenceTimeZoneResolver {
    /** Resolves [localDateTime] without silently normalizing gaps or overlaps. */
    public fun resolve(localDateTime: LocalDateTime, timeZoneId: String): LocalTimeResolution

    /**
     * Maps an explicitly supplied nonexistent local value using the offset before its gap.
     *
     * RFC 5545 assigns that interpretation to explicit DATE-TIME values. Other nonexistent local
     * candidates generated by an RRULE are still skipped when [resolve] returns
     * [LocalTimeResolution.Nonexistent]. Returning `null` declares that this resolver cannot
     * provide the RFC fallback.
     */
    public fun nonexistentInstant(localDateTime: LocalDateTime, timeZoneId: String): Instant? = null

    /**
     * Projects [instant] into local calendar fields for [timeZoneId] when the resolver supports it.
     *
     * The recurrence engine uses this optional reverse mapping to jump directly to UTC or
     * different-TZID query and `UNTIL` boundaries. Returning `null` preserves correctness through
     * scanning, but far sub-daily bounds can make that fallback expensive. Production resolvers
     * serving such queries should implement this method using the same timezone rules as [resolve].
     *
     * @return the local fields at [instant], or `null` when reverse projection is unavailable.
     */
    public fun localDateTimeAt(instant: Instant, timeZoneId: String): LocalDateTime? = null
}

/** The possible mappings from one local date-time to the instant time-line. */
public sealed interface LocalTimeResolution {
    /** The local value maps to exactly one instant. */
    public data class Valid(public val instant: Instant) : LocalTimeResolution

    /** The local value occurs twice during a backwards offset transition. */
    public data class Ambiguous(
        public val earlier: Instant,
        public val later: Instant,
    ) : LocalTimeResolution {
        init {
            require(earlier < later) { "earlier must precede later" }
        }
    }

    /** The local value does not occur during a forwards offset transition. */
    public data object Nonexistent : LocalTimeResolution
}

/** Deterministic selection policy for a local value that occurs twice. */
public enum class AmbiguousTimePolicy {
    EARLIER,
    LATER,
}
